#!/usr/bin/python3
import os

inFile = '/Users/madisonkille/tipDoc.txt'
outFile = f'/Users/{os.getlogin()}/Desktop/Tips.txt'

processedLines = {}

def fixFile():
    
    with open(inFile, 'r') as inputFile:
        for line in inputFile:
            (key, value) = line.split()
            processedLines[key] = int(value)
            
    return processedLines        

def calculateTips():

    totalTips = input("Enter the total amount of tips: ")

    totalHoursWorked = 0

    for hours in processedLines.values():
        totalHoursWorked += hours

    tipsPerHour = int(totalTips) / totalHoursWorked

    with open(outFile, 'w+') as outputFile:
        outputFile.write("The total hours worked is " + str(totalHoursWorked) + "\n")
        for employee, hours in processedLines.items():
            tipsPerPerson = hours * tipsPerHour
            outputFile.write(employee + " : " + "%.2f" % tipsPerPerson + "\n")
            


fixFile()
calculateTips()
